---

# Some handy links:
# [ip command cheat](https://access.redhat.com/sites/default/files/attachments/rh_ip_command_cheatsheet_1214_jcs_print.pdf)
# [libvirt bridge networking](https://wiki.libvirt.org/page/Networking#Bridged_networking_.28aka_.22shared_physical_device.22.29)

- name: Get MAC address for target interface
  shell: >
    ip link | grep -A1 {{ bridge_physical_nic }} | grep link | awk '{print $2}'
  register: mac_address
  changed_when: false
  tags:
    - skip_ansible_lint
    # Skip ANSIBLE0012 since we always need to run this

- name: Template physical device config
  template:
    src: physical-device.conf.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ bridge_physical_nic }}"

- name: Template bridge device config
  template:
    src: bridge-device.conf.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ bridge_network_name }}"
  notify: "Restart networking"

- meta: flush_handlers

- name: Override bridge name
  set_fact:
    bridge_name: "{{ bridge_network_name }}"
