---
# tasks file for vm-spinup

- name: Change network type ipv6
  set_fact:
    network_type: "ipv6"
  when: ipv6_enabled|bool

- name: Perform spinup
  block:
    - import_tasks: virthost-basics.yml
      when: not skip_virthost_depedencies

    - import_tasks: spinup.yml

    - import_tasks: attach-disks.yml
      when: spare_disk_attach|bool
  when: not teardown

- name: Perform teardown
  import_tasks: teardown.yml
  when: teardown
